if GetLocale() ~= "ruRU" then return end

local addonName, LazyHelper = ...

local function localeFunc(L, key) return key end
local L = setmetatable({}, {__index = localeFunc})
LazyHelper.L = L
--Translator ZamestoTV
L["greyitemssold"] = "Вы продали серые предметы за %s"
L["repairedfor"] = "Вы отремонтировали свои предметы за %s"
L["Initialized"] = "Инициализировано"
L["Durability"] = "Прочность"
L["dialogClickableURL"] = "Вы можете скопировать URL и вставить его вне клиента World of Warcraft."
L["dialogCombatLogging"] = "Расширенное ведение журнала боя еще не включено в клиенте.\n Хотите сделать это сейчас?"
L["dialogRepairItems"] = "Отремонтировать все предметы?"
L["dialogMasterlootNotSet"] = "Мастер-лут не установлен, хотите сделать это сейчас?"
L["dialogMasterlootNotSetInform"] = "Мастер-лут не установлен, хотите сообщить лидеру?"
L["dialogMasterlootNotSetMessage"] = "Привет, мастер-лут еще не установлен"
L["dialogSettingsNeedReload"] = "После изменения этих настроек интерфейс должен быть перезагружен.\n Хотите сделать это сейчас?"
L["FishingBobberGameTooltipName"] = "Поплавок для рыбалки"
L["MapCoordinatesPlayer"] = "Игрок"
L["MapCoordinatesCursor"] = "Курсор"
L["TooltipID"] = "ID"
L["TooltipSellPrice"] = "Цена продажи"
L["TooltipUnitPrice"] = "Цена за единицу"
L["TooltipPVPFlagged"] = "Отмечен для PvP"
L["TooltipUnitAFK"] = "Отсутствует"
L["TooltipUnitDND"] = "Занят"
L["TooltipGuildRank"] = "Ранг"
L["TooltipGuildNote"] = "Заметка гильдии"
L["TooltipOfficerNote"] = "Заметка офицера"
L["TooltipLevel"] = "Уровень"
L["TooltipSpecialization"] = "Специализация"
L["TooltipMythicRating"] = "Рейтинг Эпох+"
L["TooltipPvP"] = "PvP"
L["TooltipOffline"] = "Офлайн"
L["AutoLootExceptions1"] = "Чертеж" 
L["AutoLootExceptions2"] = "Выкройка" 
L["AutoLootExceptions3"] = "Формула" 
L["AutoLootExceptions4"] = "Схема" 
L["AutoLootExceptions5"] = "Эскиз" 
L["AutoLootExceptions6"] = "Рецепт"
L["AutoLootExceptions7"] = "Камень возвращения" 
L["button_ok"] = "ОК"
L["button_cancel"] = "Отмена"

L["SettingsPanel_Options"] = "Настройки"
L["SettingsPanel_Version"] = "Версия"

L["SettingsPanel_ItemRelated"] = "Связанное с предметами: прочность, расходуемые материалы и хлам"
L["SettingsPanel_ItemRelated_InfoPopup"] = "Информационное всплывающее окно"
L["SettingsPanel_ItemRelated_InfoPopup_desc"] = "Показывает информацию о прочности и расходуемых материалах при вступлении в группу или рейд. Показывает прочность у торговцев, если ремонт нужен и авторемонт отключен."
L["SettingsPanel_ItemRelated_AutoRepair"] = "Авторемонт"
L["SettingsPanel_ItemRelated_AutoRepair_desc"] = "Автоматически ремонтировать у торговца"
L["SettingsPanel_ItemRelated_SellJunk"] = "Продавать хлам"
L["SettingsPanel_ItemRelated_SellJunk_desc"] = "Автоматически продавать хлам у торговца"
L["SettingsPanel_ItemRelated_BuyReagents"] = "Покупать реагенты"
L["SettingsPanel_ItemRelated_BuyReagents_desc"] = "Автоматически покупать отслеживаемые реагенты у торговцев"

L["SettingsPanel_GroupInstance"] = "Связанное с группами и инстансами"
L["SettingsPanel_GroupInstance_NamePlates"] = "Таблички с именами"
L["SettingsPanel_GroupInstance_NamePlates_desc"] = "Автоматически отключать таблички с именами союзников в инстансах"
L["SettingsPanel_GroupInstance_CombatLogging"] = "Журнал боя"
L["SettingsPanel_GroupInstance_CombatLogging_desc"] = "Автоматически включать журнал боя в инстансах"
L["SettingsPanel_GroupInstance_MasterLoot"] = "Проверка мастер-лута"
L["SettingsPanel_GroupInstance_MasterLoot_desc"] = "Проверять мастер-лут при входе в рейдовый инстанс"
L["SettingsPanel_GroupInstance_MapClasscolors"] = "Цвета классов на карте"
L["SettingsPanel_GroupInstance_MapClasscolors_desc"] = "Показывать цвета классов на карте для членов группы"
L["SettingsPanel_GroupInstance_DisableErrors"] = "Отключить ошибки"
L["SettingsPanel_GroupInstance_DisableErrors_desc"] = "Отключить сообщения об ошибках в бою"
L["SettingsPanel_GroupInstance_ClampNameplates"] = "Фиксировать таблички"
L["SettingsPanel_GroupInstance_ClampNameplates_desc"] = "Фиксировать табличку цели вверху экрана"
L["SettingsPanel_GroupInstance_StackNameplates"] = "Складывать таблички"
L["SettingsPanel_GroupInstance_StackNameplates_desc"] = "Складывать таблички целей в групповом контенте"

L["SettingsPanel_Fishing"] = "Рыбалка"
L["SettingsPanel_Fishing_EasyFishing"] = "Упрощенная рыбалка"
L["SettingsPanel_Fishing_EasyFishing_desc"] = "Двойной щелчок правой кнопкой для заброса, когда активен бафф рыбалки"
L["SettingsPanel_Fishing_AutoLoot"] = "Автолут рыбы"
L["SettingsPanel_Fishing_AutoLoot_desc"] = "Автоматический сбор добычи в режиме рыбалки (если автолут отключен)"
L["SettingsPanel_Fishing_DisableNamePlates"] = "Отключить таблички"
L["SettingsPanel_Fishing_DisableNamePlates_desc"] = "Отключить таблички с именами в режиме рыбалки"

L["SettingsPanel_Looting"] = "Сбор добычи"
L["SettingsPanel_Looting_GreedRoll"] = "Авто жадность/трансмог"
L["SettingsPanel_Looting_GreedRoll_desc"] = "Автоматически выбирать жадность/трансмог для определенных предметов"
L["SettingsPanel_Looting_GreedRoll_dropdown_1"] = "Ничего"
L["SettingsPanel_Looting_GreedRoll_dropdown_1_desc"] = "Не выбирать жадность ни для чего"
L["SettingsPanel_Looting_GreedRoll_dropdown_2"] = "Обычные или ниже"
L["SettingsPanel_Looting_GreedRoll_dropdown_2_desc"] = "Выбирать жадность для обычных (зеленых) предметов или ниже"
L["SettingsPanel_Looting_GreedRoll_dropdown_3"] = "Редкие или ниже"
L["SettingsPanel_Looting_GreedRoll_dropdown_3_desc"] = "Выбирать жадность для редких (синих) предметов или ниже"
L["SettingsPanel_Looting_GreedRoll_dropdown_4"] = "Эпические или ниже"
L["SettingsPanel_Looting_GreedRoll_dropdown_4_desc"] = "Выбирать жадность для эпических (фиолетовых) предметов или ниже"
L["SettingsPanel_Looting_AcceptLoot"] = "Всегда принимать предупреждение о добыче"
L["SettingsPanel_Looting_AcceptLoot_desc"] = "Автоматически принимать предупреждение о добыче для всех предметов, кроме рецептов"

L["SettingsPanel_BagOrder"] = "Порядок сумок для новых предметов"
L["SettingsPanel_BagOrder_RighttoLeft"] = "Справа налево"
L["SettingsPanel_BagOrder_RighttoLeft_desc"] = "Размещать новые предметы в первой (верхней) сумке"
L["SettingsPanel_BagOrder_LefttoRight"] = "Слева направо"
L["SettingsPanel_BagOrder_LefttoRight_desc"] = "Размещать новые предметы в последней (нижней) сумке"
L["SettingsPanel_SortOrder"] = "Порядок сумок для уборки"
L["SettingsPanel_SortOrder_RighttoLeft"] = "Справа налево"
L["SettingsPanel_SortOrder_RighttoLeft_desc"] = "Сортировать предметы в первой (верхней) сумке"
L["SettingsPanel_SortOrder_LefttoRight"] = "Слева направо"
L["SettingsPanel_SortOrder_LefttoRight_desc"] = "Сортировать предметы в последней (нижней) сумке"

L["SettingsPanel_Coordinates"] = "Показывать координаты на"
L["SettingsPanel_Coordinates_WorldMap"] = "Карта мира"
L["SettingsPanel_Coordinates_WorldMap_desc"] = "Показывать координаты на карте мира"
L["SettingsPanel_Coordinates_MiniMap"] = "Миникарта"
L["SettingsPanel_Coordinates_MiniMap_desc"] = "Показывать координаты на миникарте"

L["SettingsPanel_GroupFinder"] = "Поиск групп"
L["SettingsPanel_GroupFinder_Timer"] = "Показывать таймер"
L["SettingsPanel_GroupFinder_Timer_desc"] = "Показывать таймер при использовании поиска групп"

L["SettingsPanel_BlizzardFrames"] = "Фреймы Blizzard"
L["SettingsPanel_BlizzardFrames_Actionbar"] = "Скрыть стиль панели"
L["SettingsPanel_BlizzardFrames_Actionbar_desc"] = "Убрать стилизацию панели действий Blizzard"
L["SettingsPanel_BlizzardFrames_Achievement"] = "Кнопка назад для достижений"
L["SettingsPanel_BlizzardFrames_Achievement_desc"] = "Добавить кнопку назад в окно достижений"
L["SettingsPanel_BlizzardFrames_TalkingHead"] = "Скрыть говорящую голову"
L["SettingsPanel_BlizzardFrames_TalkingHead_desc"] = "Скрыть фрейм говорящей головы"
L["SettingsPanel_BlizzardFrames_EventToast"] = "Сквозной клик по тостам событий"
L["SettingsPanel_BlizzardFrames_EventToast_desc"] = "Сквозной клик по тостам событий, чтобы можно было поворачивать камеру"

L["SettingsPanel_Frames"] = "Фреймы"
L["SettingsPanel_Frames_Unlock"] = "Разблокировать фреймы"
L["SettingsPanel_Frames_Unlock_desc"] = "Разблокировать большинство фреймов для перемещения, новое положение сохраняется"
L["SettingsPanel_Frames_SkipMovies"] = "Пропускать ролики"
L["SettingsPanel_Frames_SkipMovies_desc"] = "Автоматически пропускать ролики"
L["SettingsPanel_Frames_ClickableURL"] = "Кликабельные URL в чате"
L["SettingsPanel_Frames_ClickableURL_desc"] = "Добавить кликабельные URL в чат для их копирования"

L["SettingsPanel_AutoHideFrames"] = "Автоматически скрывать фреймы и показывать при наведении"
L["SettingsPanel_AutoHideFrames_Player"] = "Скрыть фрейм игрока"
L["SettingsPanel_AutoHideFrames_Player_desc"] = "Автоматически скрывать фрейм игрока в зонах отдыха"
L["SettingsPanel_AutoHideFrames_Sidebar"] = "Скрыть боковые панели"
L["SettingsPanel_AutoHideFrames_Sidebar_desc"] = "Автоматически скрывать боковые панели и показывать при наведении"
L["SettingsPanel_AutoHideFrames_SidebarBoth"] = "Скрыть обе боковые панели одновременно"
L["SettingsPanel_AutoHideFrames_SidebarBoth_desc"] = "Автоматически скрывать обе панели одновременно"

L["SettingsPanel_AutoHideFrames_FadeOut"] = "Затухание"
L["SettingsPanel_AutoHideFrames_FadeOut_default"] = "По умолчанию"
L["SettingsPanel_AutoHideFrames_FadeOut_slider"] = "Затухание"
L["SettingsPanel_AutoHideFrames_FadeOut_desc"] = "Время до затухания фрейма в секундах"
L["SettingsPanel_AutoHideFrames_Alpha"] = "Прозрачность"
L["SettingsPanel_AutoHideFrames_Alpha_default"] = "По умолчанию"
L["SettingsPanel_AutoHideFrames_Alpha_slider"] = "Прозрачность"
L["SettingsPanel_AutoHideFrames_Alpha_desc"] = "Насколько фрейм будет затухать. 0 — невидим, 1 — полностью видим"

L["SettingsPanel_HideFrames"] = "Скрыть фреймы"
L["SettingsPanel_HideFrames_Column1"] = "Соло"
L["SettingsPanel_HideFrames_Column2"] = "Группа"
L["SettingsPanel_HideFrames_Column3"] = "Рейд"
L["SettingsPanel_HideFrames_Objectives"] = "Задания"
L["SettingsPanel_HideFrames_Objectives_desc"] = "Скрыть трекер заданий"
L["SettingsPanel_HideFrames_Objectives_dropdown_1"] = "Всегда показывать"
L["SettingsPanel_HideFrames_Objectives_dropdown_1_desc"] = "Всегда показывать задания"
L["SettingsPanel_HideFrames_Objectives_dropdown_2"] = "Всегда скрывать"
L["SettingsPanel_HideFrames_Objectives_dropdown_2_desc"] = "Всегда скрывать задания"
L["SettingsPanel_HideFrames_Objectives_dropdown_3"] = "Скрывать в бою"
L["SettingsPanel_HideFrames_Objectives_dropdown_3_desc"] = "Скрывать задания в бою"
L["SettingsPanel_HideFrames_Objectives_dropdown_4"] = "Свернуть"
L["SettingsPanel_HideFrames_Objectives_dropdown_4_desc"] = "Свернуть все категории"
L["SettingsPanel_HideFrames_Minimap"] = "Миникарта"
L["SettingsPanel_HideFrames_Minimap_desc"] = "Скрыть миникарту"
L["SettingsPanel_HideFrames_Minimap_dropdown_1"] = "Всегда показывать"
L["SettingsPanel_HideFrames_Minimap_dropdown_1_desc"] = "Всегда показывать миникарту"
L["SettingsPanel_HideFrames_Minimap_dropdown_2"] = "Всегда скрывать"
L["SettingsPanel_HideFrames_Minimap_dropdown_2_desc"] = "Всегда скрывать миникарту"
L["SettingsPanel_HideFrames_Minimap_dropdown_3"] = "Скрывать в бою"
L["SettingsPanel_HideFrames_Minimap_dropdown_3_desc"] = "Скрывать миникарту в бою"

L["SettingsPanel_TooltipGeneral"] = "Общие"
L["SettingsPanel_TooltipGeneral_DisableCombat"] = "Отключить в бою"
L["SettingsPanel_TooltipGeneral_DisableCombat_desc"] = "Автоматически показывать или скрывать всплывающую подсказку в бою"
L["SettingsPanel_TooltipGeneral_LinkedChat"] = "Связанные предметы (чат)"
L["SettingsPanel_TooltipGeneral_LinkedChat_desc"] = "Показывать всплывающую подсказку для предметов, связанных в чате"
L["SettingsPanel_TooltipGeneral_ShowID"] = "Показывать ID/Цену за единицу"
L["SettingsPanel_TooltipGeneral_ShowID_desc"] = "Показывать ID предметов, NPC или заклинаний во всплывающей подсказке. Добавить цену за единицу для предметов"
L["SettingsPanel_TooltipGeneral_Caster"] = "Заклинатель"
L["SettingsPanel_TooltipGeneral_Caster_desc"] = "Показывать имя заклинателя во всплывающей подсказке"

L["SettingsPanel_TooltipPlayer"] = "Всплывающая подсказка NPC/Игрока"
L["SettingsPanel_TooltipPlayer_TooltipCursor"] = "Подсказка NPC у курсора"
L["SettingsPanel_TooltipPlayer_TooltipCursor_desc"] = "Показывать всплывающую подсказку игрока у курсора в открытом мире."
L["SettingsPanel_TooltipPlayer_TooltipCustom"] = "Включить настраиваемую подсказку игрока"
L["SettingsPanel_TooltipPlayer_TooltipCustom_desc"] = "Включить настраиваемую всплывающую подсказку игрока. См. настройки ниже для кастомизации."

L["SettingsPanel_TooltipCustom"] = "Настройки настраиваемой подсказки игрока"
L["SettingsPanel_TooltipCustom_ChangeName"] = "Изменить имя"
L["SettingsPanel_TooltipCustom_ChangeName_desc"] = "Включить настраиваемое имя игрока"
L["SettingsPanel_TooltipCustom_FactionIcon"] = "Иконка фракции"
L["SettingsPanel_TooltipCustom_FactionIcon_desc"] = "Включить иконку фракции"
L["SettingsPanel_TooltipCustom_GuildName"] = "Изменить название гильдии"
L["SettingsPanel_TooltipCustom_GuildName_desc"] = "Включить настраиваемое название гильдии"
L["SettingsPanel_TooltipCustom_GuildNote"] = "Заметка гильдии"
L["SettingsPanel_TooltipCustom_GuildNote_desc"] = "Включить заметку гильдии"
L["SettingsPanel_TooltipCustom_LevelSpec"] = "Уровень и специализация"
L["SettingsPanel_TooltipCustom_LevelSpec_desc"] = "Включить настраиваемый уровень, класс и специализацию"
L["SettingsPanel_TooltipCustom_MythicRating"] = "Рейтинг Эпох+"
L["SettingsPanel_TooltipCustom_MythicRating_desc"] = "Включить рейтинг Эпох+"
L["SettingsPanel_TooltipCustom_Faction"] = "Фракция"
L["SettingsPanel_TooltipCustom_Faction_desc"] = "Включить настраиваемую фракцию"

L["SettingsPanel_ViewSettings_Camera"] = "Камера"
L["SettingsPanel_ViewSettings_Camera_default"] = "По умолчанию"
L["SettingsPanel_ViewSettings_Camera_slider"] = "Масштаб"
L["SettingsPanel_ViewSettings_Camera_desc"] = "Изменить коэффициент масштабирования (лучше перезагрузить после изменения)"

L["SettingsPanel_ViewSettings_Viewport"] = "Область просмотра"
L["SettingsPanel_ViewSettings_Viewport_default"] = "По умолчанию"
L["SettingsPanel_ViewSettings_Viewport_slider"] = "Настройка"
L["SettingsPanel_ViewSettings_Viewport_label"] = "Область просмотра"
L["SettingsPanel_ViewSettings_Viewport_desc"] = "Изменить область просмотра (снизу)"

L["SettingsPanel_ViewSettings_UIScale"] = "Масштаб интерфейса"
L["SettingsPanel_ViewSettings_UIScale_default"] = "Лучший"
L["SettingsPanel_ViewSettings_UIScale_slider"] = "Настройка"
L["SettingsPanel_ViewSettings_UIScale_label"] = "Масштаб интерфейса"
L["SettingsPanel_ViewSettings_UIScale_desc"] = "Изменить масштаб интерфейса"

L["SettingsPanel_Menu_Frames"] = "Фреймы"
L["SettingsPanel_Menu_Tooltip"] = "Подсказки"
L["SettingsPanel_Menu_ViewSettings"] = "Просмотр настроек"
